package crow.wasmline.plugin.core.component.hostgen

import crow.wasmline.plugin.core.InternalWasmlineToolingApi
import java.io.File

@InternalWasmlineToolingApi
data class KotlinHostBindingsRequest(
    val witPath: File,
    val outputDirectory: File,
    val world: String,
    val kotlinPackage: String,
    val allowResources: Boolean = false,
)

@InternalWasmlineToolingApi
data class KotlinHostBindingsResult(val packageId: String, val world: String, val witSha256: String, val outputFile: File)

@InternalWasmlineToolingApi
object KotlinHostBindingsGenerator {
    const val VERSION = "1"

    fun generate(request: KotlinHostBindingsRequest): KotlinHostBindingsResult {
        require(request.kotlinPackage.matches(Regex("[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*"))) {
            "Invalid Kotlin package for Host WIT bindings: ${request.kotlinPackage}"
        }
        val witPackage = WitParser.parse(request.witPath)
        val world = witPackage.worlds[request.world]
            ?: throw WitParseException(
                "WIT world '${request.world}' was not found. Available worlds: ${witPackage.worlds.keys.sorted().joinToString()}.",
            )
        val selected = (world.imports + world.exports).distinct().map { interfaceName ->
            witPackage.interfaces[interfaceName]
                ?: throw WitParseException("World '${world.name}' references unknown interface '$interfaceName'.")
        }
        val resources = selected.flatMap { interfaceDefinition ->
            interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().map { "${interfaceDefinition.name}.${it.name}" }
        }
        if (resources.isNotEmpty() && !request.allowResources) {
            throw UnsupportedWitFeatureException(
                "Host WIT generation for world '${world.name}' requires Component resource support: ${resources.joinToString()}. " +
                    "Enable resource generation only with a resource-capable Wasmline runtime.",
            )
        }
        val emitter = KotlinEmitter(witPackage, world, selected, request.kotlinPackage, request.allowResources)
        val packageDirectory = request.kotlinPackage.split('.').fold(request.outputDirectory) { directory, segment ->
            File(directory, segment)
        }
        check(packageDirectory.mkdirs() || packageDirectory.isDirectory) {
            "Unable to create Host WIT binding output directory: ${packageDirectory.absolutePath}"
        }
        val outputFile = File(packageDirectory, "${world.name.upperCamel()}World.kt")
        outputFile.writeText(emitter.emit())
        return KotlinHostBindingsResult(witPackage.packageId, world.name, witPackage.sha256, outputFile)
    }
}

private class KotlinEmitter(
    private val witPackage: WitPackage,
    private val world: WitWorld,
    private val interfaces: List<WitInterface>,
    private val kotlinPackage: String,
    private val allowResources: Boolean,
) {
    private val types = linkedMapOf<String, WitTypeDefinition>()
    private val typeOwners = linkedMapOf<String, String>()
    private val worldObject = "${world.name.upperCamel()}World"

    init {
        interfaces.forEach { interfaceDefinition ->
            interfaceDefinition.types.forEach { definition ->
                check(types.put(definition.name, definition) == null) {
                    "Host WIT generator cannot flatten duplicate type '${definition.name}' in world '${world.name}'."
                }
                typeOwners[definition.name] = interfaceDefinition.name
            }
        }
    }

    fun emit(): String = buildString {
        appendLine("// Generated by Wasmline Host WIT generator ${KotlinHostBindingsGenerator.VERSION}. DO NOT EDIT!")
        appendLine("package $kotlinPackage")
        appendLine()
        appendLine("import crow.wasmline.WasmlineComponentContract")
        appendLine("import crow.wasmline.WasmlineComponentExport")
        appendLine("import crow.wasmline.WasmlineComponentExportBinding")
        appendLine("import crow.wasmline.WasmlineComponentFunctionBinding")
        appendLine("import crow.wasmline.WasmlineComponentFunctionId")
        appendLine("import crow.wasmline.WasmlineComponentResourceOwnership")
        appendLine("import crow.wasmline.WasmlineComponentResourceOrigin")
        appendLine("import crow.wasmline.WasmlineComponentHostAdapter")
        appendLine("import crow.wasmline.WasmlineComponentHostRegistry")
        appendLine("import crow.wasmline.WasmlineComponentImportBindingFactory")
        appendLine("import crow.wasmline.WasmlineComponentInstance")
        appendLine("import crow.wasmline.WasmlineComponentInterfaceId")
        appendLine("import crow.wasmline.WasmlineComponentValue")
        appendLine("import crow.wasmline.WasmlineGuestComponentResource")
        appendLine("import crow.wasmline.WasmlineHostComponentResource")
        appendLine("import crow.wasmline.WasmlineComponentHostResourceBinding")
        appendLine("import crow.wasmline.WasmlineComponentResourceId")
        appendLine("import crow.wasmline.WasmlineWitResult")
        appendLine("import crow.wasmline.invocation.WasmlineCallError")
        appendLine("import crow.wasmline.invocation.WasmlineCallResult")
        appendLine("import crow.wasmline.invocation.WasmlineErrorCode")
        appendLine()
        appendLine("object $worldObject {")
        appendLine("    val contract: WasmlineComponentContract = WasmlineComponentContract(")
        appendLine("        packageId = ${witPackage.packageId.quoted()},")
        appendLine("        world = ${world.name.quoted()},")
        appendLine("        witSha256 = ${witPackage.sha256.quoted()},")
        appendLine("    )")
        appendLine()
        interfaces.forEach { interfaceDefinition ->
            appendLine(
                "    private val ${interfaceDefinition.name.lowerCamel()}InterfaceId = WasmlineComponentInterfaceId.of(${interfaceId(
                    interfaceDefinition.name,
                ).quoted()})",
            )
        }
        appendLine()
        types.values.forEach { emitTypeDefinition(this, it) }
        world.exports.forEach { name -> emitExport(this, requireInterface(name)) }
        world.imports.forEach { name -> emitImport(this, requireInterface(name)) }
        emitSharedHelpers(this)
        appendLine("}")
    }

    private fun emitTypeDefinition(out: StringBuilder, definition: WitTypeDefinition) {
        when (definition) {
            is WitTypeDefinition.Record -> {
                out.appendLine("    data class ${definition.name.upperCamel()}(")
                definition.fields.forEach { field ->
                    out.appendLine("        val ${field.name.lowerCamel().identifier()}: ${kotlinType(field.type)},")
                }
                out.appendLine("    )")
                out.appendLine()
            }

            is WitTypeDefinition.Enum -> {
                out.appendLine("    enum class ${definition.name.upperCamel()} {")
                definition.cases.forEach { out.appendLine("        ${it.upperSnake().identifier()},") }
                out.appendLine("    }")
                out.appendLine()
            }

            is WitTypeDefinition.Flags -> {
                val typeName = definition.name.upperCamel()
                out.appendLine("    @JvmInline")
                out.appendLine("    value class $typeName(val bits: ULong) {")
                out.appendLine("        operator fun contains(flag: $typeName): Boolean = bits and flag.bits == flag.bits")
                out.appendLine("        operator fun plus(flag: $typeName): $typeName = $typeName(bits or flag.bits)")
                out.appendLine()
                out.appendLine("        companion object {")
                out.appendLine("            val NONE = $typeName(0UL)")
                definition.flags.forEachIndexed { index, flag ->
                    out.appendLine("            val ${flag.upperSnake().identifier()} = $typeName(1UL shl $index)")
                }
                out.appendLine("        }")
                out.appendLine("    }")
                out.appendLine()
            }

            is WitTypeDefinition.Variant -> {
                val typeName = definition.name.upperCamel()
                out.appendLine("    sealed interface $typeName {")
                definition.cases.forEach { case ->
                    val caseName = case.name.upperCamel()
                    if (case.type == null) {
                        out.appendLine("        data object $caseName : $typeName")
                    } else {
                        out.appendLine("        data class $caseName(val value: ${kotlinType(case.type)}) : $typeName")
                    }
                }
                out.appendLine("    }")
                out.appendLine()
            }

            is WitTypeDefinition.Alias -> {
                out.appendLine("    typealias ${definition.name.upperCamel()} = ${kotlinType(definition.type)}")
                out.appendLine()
            }

            is WitTypeDefinition.Resource -> if (allowResources) {
                val owner = requireInterface(typeOwners.getValue(definition.name))
                emitResourceType(out, owner, definition, owner.name in world.imports)
            }
        }
    }

    private fun emitResourceType(out: StringBuilder, owner: WitInterface, definition: WitTypeDefinition.Resource, imported: Boolean) {
        val typeName = definition.name.upperCamel()
        out.appendLine("    class $typeName internal constructor(")
        out.appendLine("        instance: WasmlineComponentInstance,")
        out.appendLine("        reference: WasmlineComponentValue.ResourceValue,")
        out.appendLine(
            "    ) : ${if (imported) "WasmlineHostComponentResource" else "WasmlineGuestComponentResource"}(instance, reference) {",
        )
        definition.methods.forEach { function ->
            val parameters = parameterDeclaration(function)
            val args = buildList {
                add("toComponentValue()")
                addAll(function.parameters.map { encodeExpression(it.type, it.name.lowerCamel().identifier()) })
            }.joinToString()
            out.appendLine(
                "        fun ${function.name.lowerCamel().identifier()}($parameters): WasmlineCallResult<${returnType(function.result)}> =",
            )
            if (imported) {
                out.appendLine(
                    "            error(\"Imported Host resource methods are invoked by the guest through the registered implementation.\")",
                )
            } else if (function.result == null) {
                out.appendLine("            invokeUnit(instance, ${resourceMethodTokenName(owner, definition, function)}, listOf($args))")
            } else {
                out.appendLine(
                    "            invokeValue(instance, ${resourceMethodTokenName(owner, definition, function)}, listOf($args)) { value ->",
                )
                out.appendLine("                ${decodeExpression(function.result, "value", "instance")}")
                out.appendLine("            }")
            }
        }
        out.appendLine("    }")
        out.appendLine()
    }

    private fun emitExport(out: StringBuilder, interfaceDefinition: WitInterface) {
        val bindingName = interfaceDefinition.name.upperCamel()
        val clientName = "${bindingName}Client"
        out.appendLine("    interface $clientName {")
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            resource.constructor?.let { constructor ->
                out.appendLine(
                    "        fun create${resource.name.upperCamel()}(${parameterDeclaration(
                        constructor,
                    )}): WasmlineCallResult<${resource.name.upperCamel()}>",
                )
            }
        }
        interfaceDefinition.functions.forEach { function ->
            out.appendLine(
                "        fun ${function.name.lowerCamel().identifier()}(${parameterDeclaration(
                    function,
                )}): WasmlineCallResult<${returnType(function.result)}>",
            )
        }
        out.appendLine("    }")
        out.appendLine()

        interfaceDefinition.functions.forEach { function ->
            out.appendLine("    private val ${exportTokenName(interfaceDefinition, function)} = WasmlineComponentExport.of(")
            out.appendLine("        ${interfaceDefinition.name.lowerCamel()}InterfaceId,")
            out.appendLine("        ${function.name.quoted()},")
            out.appendLine("    )")
        }
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            resource.constructor?.let {
                out.appendLine(
                    "    private val ${resourceConstructorTokenName(interfaceDefinition, resource)} = WasmlineComponentExport.of(",
                )
                out.appendLine("        ${interfaceDefinition.name.lowerCamel()}InterfaceId,")
                out.appendLine("        ${"[constructor]${resource.name}".quoted()},")
                out.appendLine("    )")
            }
            resource.methods.forEach { method ->
                out.appendLine(
                    "    private val ${resourceMethodTokenName(interfaceDefinition, resource, method)} = WasmlineComponentExport.of(",
                )
                out.appendLine("        ${interfaceDefinition.name.lowerCamel()}InterfaceId,")
                out.appendLine("        ${"[method]${resource.name}.${method.name}".quoted()},")
                out.appendLine("    )")
            }
        }
        out.appendLine()
        out.appendLine(
            "    val $bindingName: WasmlineComponentExportBinding<$clientName> = object : WasmlineComponentExportBinding<$clientName> {",
        )
        out.appendLine("        override val contract = this@$worldObject.contract")
        out.appendLine("        override val interfaceId = ${interfaceDefinition.name.lowerCamel()}InterfaceId")
        out.appendLine("        override val functions = listOf(")
        interfaceDefinition.functions.forEach { function ->
            out.appendLine(
                "            WasmlineComponentFunctionBinding(${exportTokenName(
                    interfaceDefinition,
                    function,
                )}, ${function.parameters.size}, ${function.result != null}),",
            )
        }
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            resource.constructor?.let {
                out.appendLine(
                    "            WasmlineComponentFunctionBinding(${resourceConstructorTokenName(
                        interfaceDefinition,
                        resource,
                    )}, ${it.parameters.size}, true),",
                )
            }
            resource.methods.forEach { method ->
                out.appendLine(
                    "            WasmlineComponentFunctionBinding(${resourceMethodTokenName(
                        interfaceDefinition,
                        resource,
                        method,
                    )}, ${method.parameters.size + 1}, ${method.result != null}),",
                )
            }
        }
        out.appendLine("        )")
        out.appendLine()
        out.appendLine("        override fun attach(instance: WasmlineComponentInstance): $clientName = object : $clientName {")
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            resource.constructor?.let { constructor -> emitResourceConstructor(out, interfaceDefinition, resource, constructor) }
        }
        interfaceDefinition.functions.forEach { function -> emitClientFunction(out, interfaceDefinition, function) }
        out.appendLine("        }")
        out.appendLine("    }")
        out.appendLine()
    }

    private fun emitResourceConstructor(
        out: StringBuilder,
        owner: WitInterface,
        resource: WitTypeDefinition.Resource,
        constructor: WitFunction,
    ) {
        val args = constructor.parameters.joinToString(", ") { encodeExpression(it.type, it.name.lowerCamel().identifier()) }
        out.appendLine(
            "            override fun create${resource.name.upperCamel()}(${parameterDeclaration(
                constructor,
            )}): WasmlineCallResult<${resource.name.upperCamel()}> =",
        )
        out.appendLine("                invokeValue(instance, ${resourceConstructorTokenName(owner, resource)}, listOf($args)) { value ->")
        out.appendLine("                    ${decodeExpression(WitType.Own(resource.name), "value", "instance")}")
        out.appendLine("                }")
    }

    private fun emitClientFunction(out: StringBuilder, owner: WitInterface, function: WitFunction) {
        val parameters = parameterDeclaration(function)
        val args = function.parameters.joinToString(", ") { encodeExpression(it.type, it.name.lowerCamel().identifier()) }
        out.appendLine(
            "            override fun ${function.name.lowerCamel().identifier()}($parameters): WasmlineCallResult<${returnType(
                function.result,
            )}> =",
        )
        if (function.result == null) {
            out.appendLine("                invokeUnit(instance, ${exportTokenName(owner, function)}, listOf($args))")
        } else {
            out.appendLine("                invokeValue(instance, ${exportTokenName(owner, function)}, listOf($args)) { value ->")
            out.appendLine("                    ${decodeExpression(function.result, "value", "instance")}")
            out.appendLine("                }")
        }
    }

    private fun emitImport(out: StringBuilder, interfaceDefinition: WitInterface) {
        val implementationName = interfaceDefinition.name.upperCamel()
        val bindingName = "${implementationName}Import"
        out.appendLine("    interface $implementationName {")
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            out.appendLine("        interface ${resource.name.upperCamel()} {")
            resource.methods.forEach { method ->
                out.appendLine(
                    "            fun ${method.name.lowerCamel().identifier()}(${parameterDeclaration(
                        method,
                    )}): ${plainReturnType(method.result)}",
                )
            }
            out.appendLine("            fun close() = Unit")
            out.appendLine("        }")
        }
        interfaceDefinition.functions.forEach { function ->
            out.appendLine(
                "        fun ${function.name.lowerCamel().identifier()}(${parameterDeclaration(
                    function,
                )}): ${plainReturnType(function.result)}",
            )
        }
        out.appendLine("    }")
        out.appendLine()
        out.appendLine("    val $bindingName: WasmlineComponentImportBindingFactory<$implementationName> =")
        out.appendLine("        object : WasmlineComponentImportBindingFactory<$implementationName> {")
        out.appendLine("            override val contract = this@$worldObject.contract")
        out.appendLine("            override val interfaceId = ${interfaceDefinition.name.lowerCamel()}InterfaceId")
        out.appendLine("            override val functions = listOf<WasmlineComponentFunctionId>(")
        interfaceDefinition.functions.forEach { function ->
            out.appendLine("                WasmlineComponentFunctionId.of(interfaceId, ${function.name.quoted()}),")
        }
        out.appendLine("            )")
        out.appendLine()
        out.appendLine(
            "            override fun bind(implementation: $implementationName, registry: WasmlineComponentHostRegistry.Builder) {",
        )
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            emitImportedResourceBinding(out, interfaceDefinition, resource)
        }
        interfaceDefinition.functions.forEachIndexed { index, function -> emitImportBinding(out, function, index) }
        out.appendLine("            }")
        out.appendLine("        }")
        out.appendLine()
        interfaceDefinition.types.filterIsInstance<WitTypeDefinition.Resource>().forEach { resource ->
            out.appendLine("    private val ${importedResourceIdName(interfaceDefinition, resource)} = WasmlineComponentResourceId(")
            out.appendLine("        ${interfaceDefinition.name.lowerCamel()}InterfaceId,")
            out.appendLine("        ${resource.name.quoted()},")
            out.appendLine("    )")
            out.appendLine("    fun create${resource.name.upperCamel()}(")
            out.appendLine("        instance: WasmlineComponentInstance,")
            out.appendLine("        implementation: $implementationName.${resource.name.upperCamel()},")
            out.appendLine("    ): ${resource.name.upperCamel()} = ${resource.name.upperCamel()}(")
            out.appendLine("        instance,")
            out.appendLine("        instance.createHostResource(${importedResourceIdName(interfaceDefinition, resource)}, implementation),")
            out.appendLine("    )")
            out.appendLine()
        }
    }

    private fun emitImportedResourceBinding(out: StringBuilder, owner: WitInterface, resource: WitTypeDefinition.Resource) {
        out.appendLine("                registry.registerResource(")
        out.appendLine("                    ${importedResourceIdName(owner, resource)},")
        out.appendLine("                    WasmlineComponentHostResourceBinding(methods = mapOf(")
        resource.methods.forEach { method ->
            out.appendLine("                        ${method.name.quoted()} to { resource, arguments ->")
            out.appendLine("                            hostCall(${method.parameters.size}, arguments) {")
            val arguments = method.parameters.mapIndexed { index, field ->
                decodeExpression(field.type, "arguments[$index]")
            }.joinToString()
            val resourceType = "$worldObject.${owner.name.upperCamel()}.${resource.name.upperCamel()}"
            val methodName = method.name.lowerCamel().identifier()
            val call = "(resource as $resourceType).$methodName($arguments)"
            if (method.result == null) {
                out.appendLine("                                $call")
                out.appendLine("                                emptyList()")
            } else {
                out.appendLine("                                val result = $call")
                out.appendLine("                                listOf(${encodeExpression(method.result, "result")})")
            }
            out.appendLine("                            }")
            out.appendLine("                        },")
        }
        out.appendLine("                    ), drop = { resource ->")
        out.appendLine(
            "                        (resource as $worldObject.${owner.name.upperCamel()}.${resource.name.upperCamel()}).close()",
        )
        out.appendLine("                    }),")
        out.appendLine("                )")
    }

    private fun emitImportBinding(out: StringBuilder, function: WitFunction, index: Int) {
        out.appendLine("                registry.register(functions[$index], WasmlineComponentHostAdapter { arguments ->")
        out.appendLine("                    hostCall(${function.parameters.size}, arguments) {")
        val invocationArgs = function.parameters.mapIndexed { parameterIndex, field ->
            if (typeContainsResource(field.type)) {
                throw UnsupportedWitFeatureException(
                    "Imported Host resource methods require native resource registration and cannot be emitted as free adapters: ${function.name}.",
                )
            }
            decodeExpression(field.type, "arguments[$parameterIndex]")
        }.joinToString(", ")
        val call = "implementation.${function.name.lowerCamel().identifier()}($invocationArgs)"
        if (function.result == null) {
            out.appendLine("                        $call")
            out.appendLine("                        emptyList()")
        } else {
            out.appendLine("                        val result = $call")
            out.appendLine("                        listOf(${encodeExpression(function.result, "result")})")
        }
        out.appendLine("                    }")
        out.appendLine("                })")
    }

    private fun emitSharedHelpers(out: StringBuilder) {
        out.appendLine("    private inline fun <T> invokeValue(")
        out.appendLine("        instance: WasmlineComponentInstance,")
        out.appendLine("        export: WasmlineComponentExport,")
        out.appendLine("        arguments: List<WasmlineComponentValue>,")
        out.appendLine("        decode: (WasmlineComponentValue) -> T,")
        out.appendLine("    ): WasmlineCallResult<T> = when (val result = instance.invoke(export, arguments)) {")
        out.appendLine("        is WasmlineCallResult.Failure -> result")
        out.appendLine("        is WasmlineCallResult.Success -> try {")
        out.appendLine(
            "            require(result.value.values.size == 1) { \"Component export returned ${'$'}{result.value.values.size} values; expected one.\" }",
        )
        out.appendLine("            WasmlineCallResult.Success(decode(result.value.values.single()))")
        out.appendLine("        } catch (error: IllegalArgumentException) {")
        out.appendLine("            bindingFailure(error.message ?: \"Component result does not match its generated WIT binding.\")")
        out.appendLine("        } catch (error: IllegalStateException) {")
        out.appendLine("            bindingFailure(error.message ?: \"Component result does not match its generated WIT binding.\")")
        out.appendLine("        }")
        out.appendLine("    }")
        out.appendLine()
        out.appendLine("    private fun invokeUnit(")
        out.appendLine("        instance: WasmlineComponentInstance,")
        out.appendLine("        export: WasmlineComponentExport,")
        out.appendLine("        arguments: List<WasmlineComponentValue>,")
        out.appendLine("    ): WasmlineCallResult<Unit> = when (val result = instance.invoke(export, arguments)) {")
        out.appendLine("        is WasmlineCallResult.Failure -> result")
        out.appendLine("        is WasmlineCallResult.Success -> if (result.value.values.isEmpty()) {")
        out.appendLine("            WasmlineCallResult.Success(Unit)")
        out.appendLine("        } else {")
        out.appendLine("            bindingFailure(\"Component export returned ${'$'}{result.value.values.size} values; expected none.\")")
        out.appendLine("        }")
        out.appendLine("    }")
        out.appendLine()
        out.appendLine("    private inline fun hostCall(")
        out.appendLine("        expectedArguments: Int,")
        out.appendLine("        arguments: List<WasmlineComponentValue>,")
        out.appendLine("        block: () -> List<WasmlineComponentValue>,")
        out.appendLine("    ): WasmlineCallResult<List<WasmlineComponentValue>> = try {")
        out.appendLine(
            "        require(arguments.size == expectedArguments) { \"Host import received ${'$'}{arguments.size} arguments; expected ${'$'}expectedArguments.\" }",
        )
        out.appendLine("        WasmlineCallResult.Success(block())")
        out.appendLine("    } catch (error: IllegalArgumentException) {")
        out.appendLine("        bindingFailure(error.message ?: \"Host import arguments do not match their generated WIT binding.\")")
        out.appendLine("    } catch (error: IllegalStateException) {")
        out.appendLine("        bindingFailure(error.message ?: \"Host import arguments do not match their generated WIT binding.\")")
        out.appendLine("    } catch (error: Throwable) {")
        out.appendLine(
            "        WasmlineCallResult.Failure(WasmlineCallError(WasmlineErrorCode.HANDLER_FAILED, error.message ?: \"Host import implementation failed.\"))",
        )
        out.appendLine("    }")
        out.appendLine()
        out.appendLine("    private fun bindingFailure(message: String): WasmlineCallResult.Failure =")
        out.appendLine("        WasmlineCallResult.Failure(WasmlineCallError(WasmlineErrorCode.INVALID_PAYLOAD, message))")
        out.appendLine()
        out.appendLine("    private fun WasmlineComponentValue.recordFields(type: String): Map<String, WasmlineComponentValue> {")
        out.appendLine(
            "        val record = this as? WasmlineComponentValue.RecordValue ?: error(\"Expected ${'$'}type record, found ${'$'}this.\")",
        )
        out.appendLine(
            "        require(record.fields.map { it.name }.distinct().size == record.fields.size) { \"${'$'}type record contains duplicate fields.\" }",
        )
        out.appendLine("        return record.fields.associate { it.name to it.value }")
        out.appendLine("    }")
        out.appendLine()
        types.values.forEach { emitCodec(out, it) }
    }

    private fun emitCodec(out: StringBuilder, definition: WitTypeDefinition) {
        val kotlinName = definition.name.upperCamel()
        val suffix = definition.name.upperCamel()
        val resourceAware = typeContainsResource(WitType.Named(definition.name))
        val instanceParameter = if (resourceAware) ", instance: WasmlineComponentInstance" else ""
        val instanceArgument = if (resourceAware) "instance" else null
        when (definition) {
            is WitTypeDefinition.Record -> {
                out.appendLine(
                    "    private fun encode$suffix(value: $kotlinName): WasmlineComponentValue = WasmlineComponentValue.RecordValue(",
                )
                out.appendLine("        listOf(")
                definition.fields.forEach { field ->
                    out.appendLine(
                        "            WasmlineComponentValue.RecordField(${field.name.quoted()}, ${encodeExpression(
                            field.type,
                            "value.${field.name.lowerCamel().identifier()}",
                        )}),",
                    )
                }
                out.appendLine("        ),")
                out.appendLine("    )")
                out.appendLine("    private fun decode$suffix(value: WasmlineComponentValue$instanceParameter): $kotlinName {")
                out.appendLine("        val fields = value.recordFields(${definition.name.quoted()})")
                definition.fields.forEach { field ->
                    out.appendLine(
                        "        require(${field.name.quoted()} in fields) { \"${definition.name} record is missing field '${field.name}'.\" }",
                    )
                }
                out.appendLine(
                    "        require(fields.size == ${definition.fields.size}) { \"${definition.name} record contains unknown fields.\" }",
                )
                out.appendLine("        return $kotlinName(")
                definition.fields.forEach { field ->
                    out.appendLine(
                        "            ${field.name.lowerCamel().identifier()} = ${decodeExpression(
                            field.type,
                            "fields.getValue(${field.name.quoted()})",
                            instanceArgument,
                        )},",
                    )
                }
                out.appendLine("        )")
                out.appendLine("    }")
            }

            is WitTypeDefinition.Enum -> {
                out.appendLine(
                    "    private fun encode$suffix(value: $kotlinName): WasmlineComponentValue = WasmlineComponentValue.EnumValue(",
                )
                out.appendLine("        when (value) {")
                definition.cases.forEach { case ->
                    out.appendLine("            $kotlinName.${case.upperSnake().identifier()} -> ${case.quoted()}")
                }
                out.appendLine("        },")
                out.appendLine("    )")
                out.appendLine("    private fun decode$suffix(value: WasmlineComponentValue$instanceParameter): $kotlinName {")
                out.appendLine(
                    "        val name = (value as? WasmlineComponentValue.EnumValue)?.name ?: error(\"Expected ${definition.name} enum, found ${'$'}value.\")",
                )
                out.appendLine("        return when (name) {")
                definition.cases.forEach { case ->
                    out.appendLine("            ${case.quoted()} -> $kotlinName.${case.upperSnake().identifier()}")
                }
                out.appendLine("            else -> error(\"Unknown ${definition.name} enum case '${'$'}name'.\")")
                out.appendLine("        }")
                out.appendLine("    }")
            }

            is WitTypeDefinition.Flags -> {
                out.appendLine(
                    "    private fun encode$suffix(value: $kotlinName): WasmlineComponentValue = WasmlineComponentValue.FlagsValue(",
                )
                out.appendLine("        buildList {")
                definition.flags.forEach { flag ->
                    out.appendLine("            if ($kotlinName.${flag.upperSnake().identifier()} in value) add(${flag.quoted()})")
                }
                out.appendLine("        },")
                out.appendLine("    )")
                out.appendLine("    private fun decode$suffix(value: WasmlineComponentValue): $kotlinName {")
                out.appendLine(
                    "        val names = (value as? WasmlineComponentValue.FlagsValue)?.names ?: error(\"Expected ${definition.name} flags, found ${'$'}value.\")",
                )
                out.appendLine("        require(names.distinct().size == names.size) { \"${definition.name} contains duplicate flags.\" }")
                out.appendLine("        var result = $kotlinName.NONE")
                out.appendLine("        names.forEach { name ->")
                out.appendLine("            result += when (name) {")
                definition.flags.forEach { flag ->
                    out.appendLine("                ${flag.quoted()} -> $kotlinName.${flag.upperSnake().identifier()}")
                }
                out.appendLine("                else -> error(\"Unknown ${definition.name} flag '${'$'}name'.\")")
                out.appendLine("            }")
                out.appendLine("        }")
                out.appendLine("        return result")
                out.appendLine("    }")
            }

            is WitTypeDefinition.Variant -> {
                out.appendLine("    private fun encode$suffix(value: $kotlinName): WasmlineComponentValue = when (value) {")
                definition.cases.forEach { case ->
                    val caseType = "$kotlinName.${case.name.upperCamel()}"
                    val encoded = case.type?.let { ", ${encodeExpression(it, "value.value")}" } ?: ""
                    out.appendLine("        is $caseType -> WasmlineComponentValue.VariantValue(${case.name.quoted()}$encoded)")
                }
                out.appendLine("    }")
                out.appendLine("    private fun decode$suffix(value: WasmlineComponentValue): $kotlinName {")
                out.appendLine(
                    "        val variant = value as? WasmlineComponentValue.VariantValue ?: error(\"Expected ${definition.name} variant, found ${'$'}value.\")",
                )
                out.appendLine("        return when (variant.discriminant) {")
                definition.cases.forEach { case ->
                    val caseType = "$kotlinName.${case.name.upperCamel()}"
                    if (case.type == null) {
                        out.appendLine(
                            "            ${case.name.quoted()} -> { require(variant.value == null) { \"Variant '${case.name}' must not have a payload.\" }; $caseType }",
                        )
                    } else {
                        out.appendLine(
                            "            ${case.name.quoted()} -> $caseType(${decodeExpression(
                                case.type,
                                "requireNotNull(variant.value) { \"Variant '${case.name}' requires a payload.\" }",
                                instanceArgument,
                            )})",
                        )
                    }
                }
                out.appendLine("            else -> error(\"Unknown ${definition.name} variant case '${'$'}{variant.discriminant}'.\")")
                out.appendLine("        }")
                out.appendLine("    }")
            }

            is WitTypeDefinition.Alias -> {
                out.appendLine(
                    "    private fun encode$suffix(value: $kotlinName): WasmlineComponentValue = ${encodeExpression(
                        definition.type,
                        "value",
                    )}",
                )
                out.appendLine(
                    "    private fun decode$suffix(value: WasmlineComponentValue$instanceParameter): $kotlinName = ${decodeExpression(
                        definition.type,
                        "value",
                        instanceArgument,
                    )}",
                )
            }

            is WitTypeDefinition.Resource -> if (allowResources) Unit
        }
        out.appendLine()
    }

    private fun parameterDeclaration(function: WitFunction): String = function.parameters.joinToString(", ") {
        "${it.name.lowerCamel().identifier()}: ${kotlinType(it.type)}"
    }

    private fun returnType(type: WitType?): String = type?.let(::kotlinType) ?: "Unit"

    private fun plainReturnType(type: WitType?): String = type?.let(::kotlinType) ?: "Unit"

    private fun kotlinType(type: WitType): String = when (type) {
        is WitType.Primitive -> when (type.name) {
            "bool" -> "Boolean"
            "s8" -> "Byte"
            "u8" -> "UByte"
            "s16" -> "Short"
            "u16" -> "UShort"
            "s32" -> "Int"
            "u32" -> "UInt"
            "s64" -> "Long"
            "u64" -> "ULong"
            "f32" -> "Float"
            "f64" -> "Double"
            "char" -> "Char"
            "string" -> "String"
            else -> error("Unknown WIT primitive '${type.name}'.")
        }

        is WitType.Named -> type.name.upperCamel()

        is WitType.ListType -> "List<${kotlinType(type.element)}>"

        is WitType.Option -> "${kotlinType(type.value)}?"

        is WitType.Tuple -> when (type.values.size) {
            2 -> "Pair<${kotlinType(type.values[0])}, ${kotlinType(type.values[1])}>"

            3 -> "Triple<${kotlinType(type.values[0])}, ${kotlinType(type.values[1])}, ${kotlinType(type.values[2])}>"

            else -> throw UnsupportedWitFeatureException(
                "Host WIT generator supports tuples with two or three elements, found ${type.values.size}.",
            )
        }

        is WitType.Result -> "WasmlineWitResult<${type.ok?.let(::kotlinType) ?: "Unit"}, ${type.error?.let(::kotlinType) ?: "Unit"}>"

        is WitType.Own -> type.resource.upperCamel()

        is WitType.Borrow -> type.resource.upperCamel()

        WitType.UnitType -> "Unit"
    }

    private fun encodeExpression(type: WitType, value: String): String = when (type) {
        is WitType.Primitive -> when (type.name) {
            "bool" -> "WasmlineComponentValue.Bool($value)"
            "s8" -> "WasmlineComponentValue.S8($value)"
            "u8" -> "WasmlineComponentValue.U8($value)"
            "s16" -> "WasmlineComponentValue.S16($value)"
            "u16" -> "WasmlineComponentValue.U16($value)"
            "s32" -> "WasmlineComponentValue.S32($value)"
            "u32" -> "WasmlineComponentValue.U32($value)"
            "s64" -> "WasmlineComponentValue.S64($value)"
            "u64" -> "WasmlineComponentValue.U64($value)"
            "f32" -> "WasmlineComponentValue.F32($value)"
            "f64" -> "WasmlineComponentValue.F64($value)"
            "char" -> "WasmlineComponentValue.CharValue($value.code.toUInt())"
            "string" -> "WasmlineComponentValue.StringValue($value)"
            else -> error("Unknown WIT primitive '${type.name}'.")
        }

        is WitType.Named -> "encode${type.name.upperCamel()}($value)"

        is WitType.ListType -> "WasmlineComponentValue.ListValue($value.map { item -> ${encodeExpression(type.element, "item")} })"

        is WitType.Option -> "WasmlineComponentValue.OptionValue($value?.let { item -> ${encodeExpression(type.value, "item")} })"

        is WitType.Tuple -> {
            val values = type.values.mapIndexed { index, child -> encodeExpression(child, tupleAccess(value, index, type.values.size)) }
            "WasmlineComponentValue.TupleValue(listOf(${values.joinToString()}))"
        }

        is WitType.Result ->
            "when ($value) { " +
                "is WasmlineWitResult.Ok -> WasmlineComponentValue.ResultValue(true, ${type.ok?.let {
                    encodeExpression(it, "$value.value")
                } ?: "null"}); " +
                "is WasmlineWitResult.Err -> WasmlineComponentValue.ResultValue(false, ${type.error?.let {
                    encodeExpression(it, "$value.error")
                } ?: "null"}) }"

        is WitType.Own -> "$value.transferToComponent()"

        is WitType.Borrow -> "$value.toComponentValue()"

        WitType.UnitType -> "WasmlineComponentValue.TupleValue(emptyList())"
    }

    private fun decodeExpression(type: WitType, value: String, instance: String? = null): String = when (type) {
        is WitType.Primitive -> {
            val componentType = when (type.name) {
                "bool" -> "Bool"
                "s8" -> "S8"
                "u8" -> "U8"
                "s16" -> "S16"
                "u16" -> "U16"
                "s32" -> "S32"
                "u32" -> "U32"
                "s64" -> "S64"
                "u64" -> "U64"
                "f32" -> "F32"
                "f64" -> "F64"
                "char" -> "CharValue"
                "string" -> "StringValue"
                else -> error("Unknown WIT primitive '${type.name}'.")
            }
            val access = if (type.name == "char") ".value.toInt().toChar()" else ".value"
            "requireNotNull($value as? WasmlineComponentValue.$componentType) { \"Expected ${type.name} value.\" }$access"
        }

        is WitType.Named -> "decode${type.name.upperCamel()}($value${if (typeContainsResource(
                type,
            )
        ) {
            ", ${requireNotNull(instance)}"
        } else {
            ""
        }})"

        is WitType.ListType -> {
            val item = decodeExpression(type.element, "item", instance)
            "requireNotNull($value as? WasmlineComponentValue.ListValue) { \"Expected list value.\" }" +
                ".values.map { item -> $item }"
        }

        is WitType.Option -> {
            val item = decodeExpression(type.value, "item", instance)
            "requireNotNull($value as? WasmlineComponentValue.OptionValue) { \"Expected option value.\" }" +
                ".value?.let { item -> $item }"
        }

        is WitType.Tuple -> {
            val tupleVar = "requireNotNull($value as? WasmlineComponentValue.TupleValue) { \"Expected tuple value.\" }.values"
            val requireSize =
                "require($tupleVar.size == ${type.values.size}) { " +
                    "\"Tuple has ${'$'}{$tupleVar.size} values; expected ${type.values.size}.\" }"
            val constructor = when (type.values.size) {
                2 -> "Pair(${decodeExpression(
                    type.values[0],
                    "$tupleVar[0]",
                    instance,
                )}, ${decodeExpression(type.values[1], "$tupleVar[1]", instance)})"

                3 -> "Triple(${decodeExpression(
                    type.values[0],
                    "$tupleVar[0]",
                    instance,
                )}, ${decodeExpression(
                    type.values[1],
                    "$tupleVar[1]",
                    instance,
                )}, ${decodeExpression(type.values[2], "$tupleVar[2]", instance)})"

                else -> throw UnsupportedWitFeatureException(
                    "Host WIT generator supports tuples with two or three elements, found ${type.values.size}.",
                )
            }
            "run { $requireSize; $constructor }"
        }

        is WitType.Result -> {
            val resultExpression =
                "requireNotNull($value as? WasmlineComponentValue.ResultValue) { \"Expected result value.\" }"
            val ok = type.ok?.let {
                "WasmlineWitResult.Ok(${decodeExpression(
                    it,
                    "requireNotNull(decoded.value) { \"Result ok payload is missing.\" }",
                    instance,
                )})"
            } ?: "run { require(decoded.value == null) { \"Unit result ok must not have a payload.\" }; WasmlineWitResult.Ok(Unit) }"
            val error = type.error?.let {
                "WasmlineWitResult.Err(${decodeExpression(
                    it,
                    "requireNotNull(decoded.value) { \"Result error payload is missing.\" }",
                    instance,
                )})"
            } ?: "run { require(decoded.value == null) { \"Unit result error must not have a payload.\" }; WasmlineWitResult.Err(Unit) }"
            "run { val decoded = $resultExpression; if (decoded.isOk) $ok else $error }"
        }

        is WitType.Own -> {
            val instanceValue = requireNotNull(instance) {
                "Decoding own<${type.resource}> requires a Component instance."
            }
            "run { val resource = requireNotNull($value as? WasmlineComponentValue.ResourceValue) { " +
                "\"Expected own<${type.resource}> resource.\" }; " +
                "require(resource.ownership == WasmlineComponentResourceOwnership.OWN) { " +
                "\"Expected owned ${type.resource} resource.\" }; " +
                "require(resource.origin == WasmlineComponentResourceOrigin.GUEST) { " +
                "\"Expected guest ${type.resource} resource.\" }; " +
                "${type.resource.upperCamel()}($instanceValue, resource) }"
        }

        is WitType.Borrow -> throw UnsupportedWitFeatureException(
            "Borrowed resource decoding is only supported for imported Host resource callbacks.",
        )

        WitType.UnitType -> "Unit"
    }

    private fun typeContainsResource(type: WitType, visiting: MutableSet<String> = mutableSetOf()): Boolean = when (type) {
        is WitType.Own, is WitType.Borrow -> true

        is WitType.ListType -> typeContainsResource(type.element, visiting)

        is WitType.Option -> typeContainsResource(type.value, visiting)

        is WitType.Tuple -> type.values.any { typeContainsResource(it, visiting) }

        is WitType.Result -> listOfNotNull(type.ok, type.error).any { typeContainsResource(it, visiting) }

        is WitType.Named -> if (!visiting.add(type.name)) {
            false
        } else {
            when (val definition = types[type.name]) {
                is WitTypeDefinition.Record -> definition.fields.any { typeContainsResource(it.type, visiting) }
                is WitTypeDefinition.Variant -> definition.cases.mapNotNull(WitCase::type).any { typeContainsResource(it, visiting) }
                is WitTypeDefinition.Alias -> typeContainsResource(definition.type, visiting)
                is WitTypeDefinition.Resource -> true
                else -> false
            }.also { visiting.remove(type.name) }
        }

        else -> false
    }

    private fun tupleAccess(value: String, index: Int, size: Int): String = when (size) {
        2 -> if (index == 0) "$value.first" else "$value.second"

        3 -> when (index) {
            0 -> "$value.first"
            1 -> "$value.second"
            else -> "$value.third"
        }

        else -> error("Unsupported tuple size $size")
    }

    private fun exportTokenName(owner: WitInterface, function: WitFunction): String =
        "${owner.name.lowerCamel()}${function.name.upperCamel()}Export"

    private fun resourceConstructorTokenName(owner: WitInterface, resource: WitTypeDefinition.Resource): String =
        "${owner.name.lowerCamel()}${resource.name.upperCamel()}ConstructorExport"

    private fun resourceMethodTokenName(owner: WitInterface, resource: WitTypeDefinition.Resource, method: WitFunction): String =
        "${owner.name.lowerCamel()}${resource.name.upperCamel()}${method.name.upperCamel()}Export"

    private fun importedResourceIdName(owner: WitInterface, resource: WitTypeDefinition.Resource): String =
        "${owner.name.lowerCamel()}${resource.name.upperCamel()}ResourceId"

    private fun requireInterface(name: String): WitInterface = requireNotNull(witPackage.interfaces[name])

    private fun interfaceId(name: String): String {
        val base = witPackage.packageId.substringBefore('@')
        val version = witPackage.packageId.substringAfter('@', missingDelimiterValue = "")
        return "$base/$name${if (version.isEmpty()) "" else "@$version"}"
    }
}

private val KOTLIN_KEYWORDS = setOf(
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null",
    "object", "package", "return", "super", "this", "throw", "true", "try", "typealias", "typeof", "val", "var", "when", "while",
)

private fun String.identifier(): String = if (this in KOTLIN_KEYWORDS) "`$this`" else this

private fun String.quoted(): String = buildString {
    append('"')
    this@quoted.forEach { char ->
        when (char) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(char)
        }
    }
    append('"')
}

private fun String.words(): List<String> = split('-', '_').filter(String::isNotEmpty)

private fun String.upperCamel(): String = words().joinToString("") { word ->
    word.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
}

private fun String.lowerCamel(): String = upperCamel().replaceFirstChar { it.lowercase() }

private fun String.upperSnake(): String = words().joinToString("_") { it.uppercase() }
