org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

kotlin.code.style=official

android.sync.suppressAgpWarnings=GENERIC,UNSUPPORTED_PROJECT_OPTION_USE
android.useAndroidX=true
android.nonTransitiveRClass=true
android.injected.testOnly=false

kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

# Wasmline configuration
wasmline.version=1.0.0
wasmtime.version=48.0.1
