plugins {
  `kotlin-dsl`
}

dependencies {
  implementation(libs.gradle.kotlin.plugin)
}


// Embed libs into the project script
// src cannot access Gradle auto-generated libs; generate libsEx separately to resolve dependency info from libs.versions.toml
val generateLibsTask = tasks.register("generateLibs") {
  group = "mordecaix-build-logic"
  val versionCatalogs = project.extensions.getByType(VersionCatalogsExtension::class).named("libs")
  val libsList = versionCatalogs.libraryAliases.map { it.replace(".", "-") }
  val versionList = versionCatalogs.versionAliases.map { it.replace(".", "-") }
  val pluginsList = versionCatalogs.pluginAliases.map { it.replace(".", "-") }
  inputs.property("libsList", libsList)
  inputs.property("versionList", versionList)
  inputs.property("pluginsList", pluginsList)
  // Generated file lives in the module's build directory
  val outputDir = project.layout.buildDirectory.dir(
    "generated/sources/libs/${SourceSet.MAIN_SOURCE_SET_NAME}"
  )
  outputs.dir(outputDir)
  doLast {
    val file = outputDir.get().asFile.resolve("Libs.kt")
    file.parentFile.mkdirs()
    file.delete()
    file.writeText(getLibsClass(libsList, versionList, pluginsList))
  }
}


fun getLibsClass(
  libsList: List<String>,
  versionList: List<String>,
  pluginsList: List<String>
) : String = """
// Generated by mordecaix-build-logic/base/build.gradle.kts

package buildlogic

import org.gradle.api.Project
import org.gradle.api.artifacts.ExternalModuleDependencyBundle
import org.gradle.api.artifacts.MinimalExternalModuleDependency
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.api.artifacts.VersionConstraint
import org.gradle.kotlin.dsl.extra
import org.gradle.kotlin.dsl.getByType
import org.gradle.plugin.use.PluginDependency

val Project.libsEx: LibsEx
  get() = if (extra.has("libsEx")) extra.get("libsEx") as LibsEx else {
    LibsEx(this).also { extra.set("libsEx", it) }
  }

class LibsEx(val project: Project) {
  val versions = Versions()
  val plugins = Plugins()
  
  ${libsList.joinToString("\n  ") { 
    "val `$it`: MinimalExternalModuleDependency get() = libsLibrary(\"$it\")" 
  }}
  
  private val libs = project.extensions.getByType(VersionCatalogsExtension::class).named("libs")
  private fun libsLibrary(alias: String) = libs.findLibrary(alias).get().get()
  private fun libsBundle(alias: String) = libs.findBundle(alias).get().get()
  private fun libsVersion(alias: String) = libs.findVersion(alias).get()
  private fun libsPlugin(alias: String) = libs.findPlugin(alias).get().get()
  
  inner class Versions {
    ${versionList.joinToString("\n    ") { 
      "val `$it`: VersionConstraint get() = libsVersion(\"$it\")"
    }}
  }
  
  inner class Plugins {
    ${pluginsList.joinToString("\n    ") {
      "val `$it`: PluginDependency get() = libsPlugin(\"$it\")"
    }}
  }
}
""".trimIndent()

// Register in compile and dependency classpath; task auto-runs during compilation to generate corresponding code
sourceSets {
  main {
    kotlin.srcDir(generateLibsTask)
  }
}
