

package crow.wasmline.kotlin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link crow.wasmline.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("/Users/crowf/develop/github/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  private void run(String fileName) {
    runTest("/Users/crowf/develop/github/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box/" + fileName);
  }

  @Test
  @TestMetadata("01_emptyService.kt")
  public void test01_emptyService() {
    run("01_emptyService.kt");
  }

  @Test
  @TestMetadata("02_simpleMethod.kt")
  public void test02_simpleMethod() {
    run("02_simpleMethod.kt");
  }

  @Test
  @TestMetadata("03_parameterService.kt")
  public void test03_parameterService() {
    run("03_parameterService.kt");
  }

  @Test
  @TestMetadata("04_multiMethod.kt")
  public void test04_multiMethod() {
    run("04_multiMethod.kt");
  }

  @Test
  @TestMetadata("05_complexTypes.kt")
  public void test05_complexTypes() {
    run("05_complexTypes.kt");
  }

  @Test
  @TestMetadata("06_linkBindPattern.kt")
  public void test06_linkBindPattern() {
    run("06_linkBindPattern.kt");
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("/Users/crowf/develop/github/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }
}
