

package crow.wasmline.kotlin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link crow.wasmline.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("D:/fish/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("D:/fish/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("bindAsSelectsRequestedContract.kt")
  public void testBindAsSelectsRequestedContract() {
    runTest("D:/fish/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box/bindAsSelectsRequestedContract.kt");
  }

  @Test
  @TestMetadata("echoProxyRoundTrip.kt")
  public void testEchoProxyRoundTrip() {
    runTest("D:/fish/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box/echoProxyRoundTrip.kt");
  }

  @Test
  @TestMetadata("linkSelectsGeneratedBridge.kt")
  public void testLinkSelectsGeneratedBridge() {
    runTest("D:/fish/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box/linkSelectsGeneratedBridge.kt");
  }

  @Test
  @TestMetadata("zeroArgUnitBridgeRoundTrip.kt")
  public void testZeroArgUnitBridgeRoundTrip() {
    runTest("D:/fish/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/box/zeroArgUnitBridgeRoundTrip.kt");
  }
}
