

package crow.wasmline.kotlin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link crow.wasmline.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("/home/crowf/develop/github/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  private void run(String fileName) {
    runTest("/home/crowf/develop/github/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  @TestMetadata("01_notWasmlineService.kt")
  public void test01_notWasmlineService() {
    run("01_notWasmlineService.kt");
  }

  @Test
  @TestMetadata("02_emptyWasmlineService.kt")
  public void test02_emptyWasmlineService() {
    run("02_emptyWasmlineService.kt");
  }

  @Test
  @TestMetadata("03_typeMismatchExample.kt")
  public void test03_typeMismatchExample() {
    run("03_typeMismatchExample.kt");
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("/home/crowf/develop/github/wasmline/wasmline-multiplatform/wasmline-kotlin-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }
}
