#!/usr/bin/env bash

if [[ -n "${WASMLINE_PATHS_SH_LOADED:-}" ]]; then
  return 0
fi
WASMLINE_PATHS_SH_LOADED=1

WASMLINE_SHELL_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WASMLINE_SCRIPTS_ROOT="$(cd "${WASMLINE_SHELL_LIB_DIR}/../.." && pwd)"
WASMLINE_PROJECT_ROOT="$(cd "${WASMLINE_SCRIPTS_ROOT}/.." && pwd)"
WASMLINE_BUILD_ROOT="${WASMLINE_PROJECT_ROOT}/build"
WASMLINE_PLATFORMS_ROOT="${WASMLINE_BUILD_ROOT}/platforms"

readonly WASMLINE_SHELL_LIB_DIR
readonly WASMLINE_SCRIPTS_ROOT
readonly WASMLINE_PROJECT_ROOT
readonly WASMLINE_BUILD_ROOT
readonly WASMLINE_PLATFORMS_ROOT
