package wasmline:rpc@1.0.0;

world plugin {
  import host: interface {
    record request {
      action: string,
      codec: string,
      payload: list<u8>
    }

    record rpc-error {
      code: string,
      message: string,
      details: list<u8>
    }

    invoke: func(request: request) -> result<list<u8>, rpc-error>;
  }

  export plugin: interface {
    record request {
      action: string,
      codec: string,
      payload: list<u8>
    }

    record rpc-error {
      code: string,
      message: string,
      details: list<u8>
    }

    invoke: func(request: request) -> result<list<u8>, rpc-error>;
  }
}
