package crow.wasmline.gradle.tasks

import crow.wasmline.gradle.trust.TrustedPublicKeySpec
import crow.wasmline.gradle.trust.WasmlineTrustedPublicKeySpecCodec
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.nio.charset.StandardCharsets

/** Generates the configured Host trust set as common Kotlin source. */
@CacheableTask
internal abstract class WasmlineGenerateTrustedKeysTask : DefaultTask() {
    @get:Input
    abstract val inlinePublicKeySpecs: ListProperty<String>

    @get:Input
    abstract val publicKeyFileSpecs: ListProperty<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val publicKeyFiles: ConfigurableFileCollection

    @get:Input
    abstract val kotlinPackage: Property<String>

    @get:Input
    abstract val objectName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val keys = inlinePublicKeySpecs.get().map(WasmlineTrustedPublicKeySpecCodec::decode) +
            publicKeyFileSpecs.get().map(WasmlineTrustedPublicKeySpecCodec::decode)
        val resolvedKeys = keys.map(::resolvePublicKey)
        validate(resolvedKeys)

        val packageName = kotlinPackage.get()
        val generatedObjectName = objectName.get()
        requireKotlinPackage(packageName)
        requireKotlinIdentifier(generatedObjectName, "Generated trust object name")

        val output = outputDirectory.get().asFile
        project.delete(output)
        val sourceFile = output.resolve(packageName.replace('.', File.separatorChar)).resolve("$generatedObjectName.kt")
        sourceFile.parentFile.mkdirs()
        sourceFile.writeText(renderSource(packageName, generatedObjectName, resolvedKeys), StandardCharsets.UTF_8)
    }

    private fun resolvePublicKey(spec: TrustedPublicKeySpec): ResolvedPublicKey = ResolvedPublicKey(
        algorithm = spec.algorithm,
        keyId = spec.keyId,
        publicKeyHex = spec.inlinePublicKeyHex ?: spec.publicKeyFile
            ?.let { file ->
                require(file.isFile) { "Configured public-key file does not exist: ${file.absolutePath}" }
                file.readText(StandardCharsets.UTF_8).trim()
            }
            ?: error("Trusted public-key specification has no key source."),
    )

    private fun validate(keys: List<ResolvedPublicKey>) {
        require(keys.isNotEmpty()) { "At least one trusted public key is required." }
        val declaredKeys = mutableSetOf<Pair<String, String?>>()
        keys.forEach { key ->
            require(key.algorithm.isNotBlank()) { "Public-key algorithm must not be blank." }
            require(key.keyId == null || key.keyId.isNotBlank()) { "Public-key keyId must not be blank." }
            require(key.publicKeyHex.length % 2 == 0 && key.publicKeyHex.all(::isAsciiHexDigit)) {
                "Public key for ${key.displayName()} must be an even-length hexadecimal string."
            }
            require(declaredKeys.add(key.algorithm to key.keyId)) {
                "Duplicate public key declaration for ${key.displayName()}. Use a distinct keyId when rotating keys."
            }
        }
    }

    private fun requireKotlinPackage(value: String) {
        require(value.split('.').all(::isKotlinIdentifier)) {
            "Generated trust Kotlin package '$value' is invalid."
        }
    }

    private fun requireKotlinIdentifier(value: String, label: String) {
        require(isKotlinIdentifier(value)) { "$label '$value' is invalid." }
    }

    private fun isKotlinIdentifier(value: String): Boolean = value.isNotEmpty() && (value.first() == '_' || value.first().isLetter()) &&
        value.drop(1).all { character -> character == '_' || character.isLetterOrDigit() }

    private fun isAsciiHexDigit(character: Char): Boolean = character in '0'..'9' || character in 'a'..'f' || character in 'A'..'F'

    private fun renderSource(packageName: String, generatedObjectName: String, keys: List<ResolvedPublicKey>): String = buildString {
        appendLine("// Generated by the Wasmline Gradle plugin. Do not edit.")
        appendLine("package $packageName")
        appendLine()
        appendLine("import crow.wasmline.loader.WasmlineTrustedKeySet")
        appendLine("import crow.wasmline.loader.WasmlineTrustedKeys")
        appendLine()
        appendLine("/** Trusted public keys configured through wasmline.trust. */")
        appendLine("public object $generatedObjectName : WasmlineTrustedKeys by WasmlineTrustedKeySet.Builder()")
        keys.forEach { key ->
            appendLine("    .addHex(")
            appendLine("        algorithm = ${key.algorithm.kotlinStringLiteral()},")
            appendLine("        keyId = ${key.keyId?.kotlinStringLiteral() ?: "null"},")
            appendLine("        publicKeyHex = ${key.publicKeyHex.kotlinStringLiteral()},")
            appendLine("    )")
        }
        appendLine("    .build()")
    }

    private fun String.kotlinStringLiteral(): String = buildString {
        append('"')
        this@kotlinStringLiteral.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(character)
            }
        }
        append('"')
    }

    private fun ResolvedPublicKey.displayName(): String = "algorithm '$algorithm'${keyId?.let { ", keyId '$it'" }.orEmpty()}"

    private data class ResolvedPublicKey(val algorithm: String, val keyId: String?, val publicKeyHex: String)
}
