package crow.wasmline.plugin.core.component.hostgen

import crow.wasmline.WasmlineComponentContract
import org.jetbrains.kotlin.cli.common.ExitCode
import org.jetbrains.kotlin.cli.jvm.K2JVMCompiler
import java.io.File
import kotlin.io.path.createTempDirectory
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class KotlinHostBindingsGeneratorTest {
    @Test
    fun parsesAllComponentModelSamples() {
        val samples = sampleRoot()
        val expected = mapOf(
            "math" to Triple("wasmline:math@0.1.0", "math-plugin", 1),
            "calculator" to Triple("wasmline:calculator@0.1.0", "calculator-plugin", 2),
            "fileio" to Triple("wasmline:fileio@0.1.0", "fileio-plugin", 1),
            "function" to Triple("wasmline:functions@0.1.0", "function-plugin", 2),
            "kv" to Triple("wasmline:kv@0.1.0", "kv-plugin", 2),
        )

        expected.forEach { (name, expectation) ->
            val parsed = WitParser.parse(File(samples, name))
            assertEquals(expectation.first, parsed.packageId)
            assertEquals(expectation.second, parsed.worlds.values.single().name)
            assertEquals(expectation.third, parsed.interfaces.size)
            assertTrue(parsed.sha256.matches(Regex("[0-9a-f]{64}")))
        }
    }

    @Test
    fun generatesMathAndCalculatorHostFacadesWithTypedErrorLayering() = withGeneratorDirectory { output ->
        val samples = sampleRoot()
        val math = KotlinHostBindingsGenerator.generate(
            KotlinHostBindingsRequest(
                witPath = File(samples, "math"),
                outputDirectory = output,
                world = "math-plugin",
                kotlinPackage = "generated.math",
            ),
        )
        val calculator = KotlinHostBindingsGenerator.generate(
            KotlinHostBindingsRequest(
                witPath = File(samples, "calculator"),
                outputDirectory = output,
                world = "calculator-plugin",
                kotlinPackage = "generated.calculator",
            ),
        )

        val mathSource = math.outputFile.readText()
        assertTrue(mathSource.startsWith("// Generated by Wasmline Host WIT generator 1. DO NOT EDIT!"))
        assertTrue(mathSource.contains("interface MathClient"))
        assertTrue(mathSource.contains("WasmlineCallResult<WasmlineWitResult<Double, MathError>>"))
        assertTrue(mathSource.contains("WasmlineComponentExportBinding<MathClient>"))
        assertTrue(mathSource.contains("witSha256 = \"${math.witSha256}\""))

        val calculatorSource = calculator.outputFile.readText()
        assertTrue(calculatorSource.contains("interface CalculatorClient"))
        assertTrue(calculatorSource.contains("interface HostLog"))
        assertTrue(calculatorSource.contains("WasmlineComponentImportBindingFactory<HostLog>"))
        assertTrue(calculatorSource.contains("wasmline:calculator/host-log@0.1.0"))
        assertTrue(calculatorSource.contains("WasmlineWitResult<Calculation, CalculatorError>"))
        assertTrue(calculatorSource.none { it == '\r' })
    }

    @Test
    fun rejectsResourceWorldsUntilResourceCapabilityIsEnabled() = withGeneratorDirectory { output ->
        val samples = sampleRoot()
        mapOf(
            "fileio" to "file-io.file",
            "function" to "host-callbacks.callback",
            "kv" to "key-value.bucket",
        ).forEach { (sample, resource) ->
            val parsed = WitParser.parse(File(samples, sample))
            val failure = assertFailsWith<UnsupportedWitFeatureException> {
                KotlinHostBindingsGenerator.generate(
                    KotlinHostBindingsRequest(
                        witPath = File(samples, sample),
                        outputDirectory = output,
                        world = parsed.worlds.values.single().name,
                        kotlinPackage = "generated.$sample",
                    ),
                )
            }
            assertTrue(failure.message.orEmpty().contains(resource), failure.message)
        }
    }

    @Test
    fun rejectsAsyncComponentTypesWithFeatureSpecificDiagnostics() = withGeneratorDirectory { root ->
        listOf("future<u32>", "stream<u8>", "pollable", "error-context").forEach { type ->
            val wit = File(root, type.substringBefore('<')).apply { mkdirs() }
            File(wit, "world.wit").writeText(
                """
                package sample:async@1.0.0;
                interface api { value: func(input: $type); }
                world plugin { export api; }
                """.trimIndent(),
            )

            val failure = assertFailsWith<UnsupportedWitFeatureException> {
                KotlinHostBindingsGenerator.generate(
                    KotlinHostBindingsRequest(
                        witPath = wit,
                        outputDirectory = File(root, "generated-${type.substringBefore('<')}"),
                        world = "plugin",
                        kotlinPackage = "generated.async",
                    ),
                )
            }
            assertTrue(failure.message.orEmpty().contains("WIT async type '${type.substringBefore('<')}'"), failure.message)
            assertTrue(failure.message.orEmpty().contains("async Component Store"), failure.message)
        }
    }

    @Test
    fun separatesRootPackageDeclarationsFromDependencyPackages() = withGeneratorDirectory { root ->
        val wit = File(root, "wit").apply { mkdirs() }
        File(wit, "types.wit").writeText(
            """
            package sample:root@1.0.0;
            interface values { value: func() -> u32; }
            """.trimIndent(),
        )
        File(wit, "world.wit").writeText(
            """
            package sample:root@1.0.0;
            world plugin { export values; }
            """.trimIndent(),
        )
        val dependency = File(wit, "deps/dependency.wit").apply {
            parentFile.mkdirs()
            writeText("package sample:dependency@2.0.0; interface unused {}")
        }

        val first = WitParser.parse(wit)
        assertEquals("sample:root@1.0.0", first.packageId)
        val firstDigest = first.sha256
        dependency.appendText("\n// digest change")
        val second = WitParser.parse(wit)
        assertEquals("sample:root@1.0.0", second.packageId)
        assertTrue(firstDigest != second.sha256)
    }

    @Test
    fun generatedMathAndCalculatorFacadesCompileAgainstTheRuntime() = withGeneratorDirectory { root ->
        val generated = File(root, "generated")
        val samples = sampleRoot()
        val sources = listOf(
            KotlinHostBindingsGenerator.generate(
                KotlinHostBindingsRequest(
                    File(samples, "math"),
                    generated,
                    "math-plugin",
                    "generated.math",
                ),
            ).outputFile,
            KotlinHostBindingsGenerator.generate(
                KotlinHostBindingsRequest(
                    File(samples, "calculator"),
                    generated,
                    "calculator-plugin",
                    "generated.calculator",
                ),
            ).outputFile,
        )
        val output = File(root, "classes")
        val runtimeJar = File(WasmlineComponentContract::class.java.protectionDomain.codeSource.location.toURI())
        val stdlibJar = File(Unit::class.java.protectionDomain.codeSource.location.toURI())
        val arguments = arrayOf(
            "-no-reflect",
            "-classpath",
            listOf(runtimeJar, stdlibJar).joinToString(File.pathSeparator, transform = File::getAbsolutePath),
            "-d",
            output.absolutePath,
            *sources.map(File::getAbsolutePath).toTypedArray(),
        )

        val result = K2JVMCompiler().exec(System.err, *arguments)

        assertEquals(ExitCode.OK, result)
        assertTrue(File(output, "generated/math/MathPluginWorld.class").isFile)
        assertTrue(File(output, "generated/calculator/CalculatorPluginWorld.class").isFile)
    }

    @Test
    fun generatesAndCompilesExportedResourceFacades() = withGeneratorDirectory { root ->
        val generated = File(root, "generated")
        val result = KotlinHostBindingsGenerator.generate(
            KotlinHostBindingsRequest(
                File(sampleRoot(), "fileio"),
                generated,
                "fileio-plugin",
                "generated.fileio",
                allowResources = true,
            ),
        )
        val source = result.outputFile.readText()
        assertTrue(source.contains("class File internal constructor("))
        assertTrue(source.contains(": WasmlineGuestComponentResource(instance, reference)"))
        assertTrue(source.contains("fun createFile("))
        assertTrue(source.contains("[constructor]file"))
        assertTrue(source.contains("[method]file.read"))

        val output = File(root, "classes")
        val runtimeJar = File(WasmlineComponentContract::class.java.protectionDomain.codeSource.location.toURI())
        val stdlibJar = File(Unit::class.java.protectionDomain.codeSource.location.toURI())
        val compile = K2JVMCompiler().exec(
            System.err,
            "-no-reflect",
            "-classpath",
            listOf(runtimeJar, stdlibJar).joinToString(File.pathSeparator, transform = File::getAbsolutePath),
            "-d",
            output.absolutePath,
            result.outputFile.absolutePath,
        )

        assertEquals(ExitCode.OK, compile)
        assertTrue(File(output, "generated/fileio/FileioPluginWorld\$File.class").isFile)
    }

    @Test
    fun generatesAndCompilesImportedCallbackResourceFacade() = withGeneratorDirectory { root ->
        val result = KotlinHostBindingsGenerator.generate(
            KotlinHostBindingsRequest(
                File(sampleRoot(), "function"),
                File(root, "generated"),
                "function-plugin",
                "generated.function",
                allowResources = true,
            ),
        )
        val source = result.outputFile.readText()
        assertTrue(source.contains("interface Callback"))
        assertTrue(source.contains("WasmlineComponentHostResourceBinding"))
        assertTrue(source.contains("fun createCallback("))
        assertTrue(source.contains(": WasmlineHostComponentResource(instance, reference)"))

        val output = File(root, "classes")
        val runtimeJar = File(WasmlineComponentContract::class.java.protectionDomain.codeSource.location.toURI())
        val stdlibJar = File(Unit::class.java.protectionDomain.codeSource.location.toURI())
        val compile = K2JVMCompiler().exec(
            System.err,
            "-no-reflect",
            "-classpath",
            listOf(runtimeJar, stdlibJar).joinToString(File.pathSeparator, transform = File::getAbsolutePath),
            "-d",
            output.absolutePath,
            result.outputFile.absolutePath,
        )

        assertEquals(ExitCode.OK, compile)
        assertTrue(File(output, "generated/function/FunctionPluginWorld\$Callback.class").isFile)
    }

    @Test
    fun generatesAndCompilesMultipleResourcesWithNestedOwnedResults() = withGeneratorDirectory { root ->
        val result = KotlinHostBindingsGenerator.generate(
            KotlinHostBindingsRequest(
                File(sampleRoot(), "kv"),
                File(root, "generated"),
                "kv-plugin",
                "generated.kv",
                allowResources = true,
            ),
        )
        val source = result.outputFile.readText()
        assertTrue(source.contains("class Bucket internal constructor("))
        assertTrue(source.contains("class WatchHandle internal constructor("))
        assertTrue(source.contains("WasmlineWitResult<Bucket, KvError>"))
        assertTrue(source.contains("WasmlineWitResult<WatchHandle, KvError>"))
        assertTrue(source.contains("Pair<List<Entry>, String?>"))
        assertTrue(source.contains("interface HostClock"))

        val output = File(root, "classes")
        val runtimeJar = File(WasmlineComponentContract::class.java.protectionDomain.codeSource.location.toURI())
        val stdlibJar = File(Unit::class.java.protectionDomain.codeSource.location.toURI())
        val compile = K2JVMCompiler().exec(
            System.err,
            "-no-reflect",
            "-classpath",
            listOf(runtimeJar, stdlibJar).joinToString(File.pathSeparator, transform = File::getAbsolutePath),
            "-d",
            output.absolutePath,
            result.outputFile.absolutePath,
        )

        assertEquals(ExitCode.OK, compile)
        assertTrue(File(output, "generated/kv/KvPluginWorld\$Bucket.class").isFile)
        assertTrue(File(output, "generated/kv/KvPluginWorld\$WatchHandle.class").isFile)
    }

    private fun sampleRoot(): File {
        val resourceRoot = checkNotNull(javaClass.classLoader.getResource("fixtures/component-model-wit-samples")) {
            "Unable to locate component model WIT samples test fixture."
        }
        return File(resourceRoot.toURI())
    }
}

private inline fun withGeneratorDirectory(block: (File) -> Unit) {
    val directory = createTempDirectory("wasmline-host-wit-generator-test").toFile()
    try {
        block(directory)
    } finally {
        directory.deleteRecursively()
    }
}
